### ISSUE TITLE
First Good Issue Svelte Basic App

### ISSUE THREAD

**Issue by 047pegasus** [047pegasus/devism#1]
**Add a basic Svelte project to the repo by learning from a tutorial.**

Create a folder with the project name and add all files for project in that folder. Add name of the contributor in the contributor.txt of the project submitted folder.

**Sample Folder Structure:**

<contributor_name> 
     --- <main_app_folder> (add app files in this sub folder)
     --- Contributor.txt (contains name of the contributor)

_Don't add just a boiler plate project, atleast make a decent roject before creating a PR as well as follow the CONTRIBUTING.md guidelines to contribute to the repo._

**Comment by akadeepesh** [comment]
i can do this, please assign it to me!

**Comment by 047pegasus** [comment]
> i can do this, please assign it to me!

Sure @akadeepesh you may continue.. assigned it you.

**Comment by akadeepesh** [comment]
done.

**Comment by utsxvrai** [comment]
@047pegasus  pls assign it to me, I wanted to work on it!

**Comment by Sachan-aditya** [comment]
Can you assign me this issue ? Also one more thing do i have to work on a new branch after forking ?

**Comment by Hemant2335** [comment]
@047pegasus Could you please assign me this issue to me

**Comment by 047pegasus** [comment]
Assigned it you @Hemant2335 @utsxvrai and @Sachan-aditya Start working on it!! Cheers 👨‍💻

**Comment by ShashwatPS** [comment]
Hey @047pegasus can you assign me this issue ? Would like to work on it.

**Comment by 047pegasus** [comment]
Sure @ShashwatPS . You may also Contribute!! ✅

**Comment by 047pegasus** [comment]
Issue expired!! Well done everyone!! ✅🚀
