### ISSUE TITLE
my-svelte-app 

### ISSUE THREAD

**Issue by utsxvrai** [047pegasus/devism#27]
pls  assign this issue to me !

**Comment by 047pegasus** [comment]
Assigned done ✅

**Comment by adarsh1219** [comment]
sir could you please assign me this issue

**Comment by adarsh1219** [comment]
please assign me this issue

**Comment by 047pegasus** [comment]
Done @adarsh1219  assigned it you also. ✅

**Comment by 047pegasus** [comment]
Completed issue!! ✅
