### ISSUE TITLE
Add a React Dashboard Application Page.

### ISSUE THREAD

**Issue by 047pegasus** [047pegasus/devism#3]
**Add a self developed React Dashboard project to the repo by learning from a tutorial available online.**

Create a folder with the project name and add all files for project in that folder. Add name of the contributor in the contributor.txt of the project submitted folder.

**Sample Folder Structure:**

<contributor_name>
--- <main_app_folder> (add app files in this sub folder)
---  Contributor.txt (contains name of the contributor)

_Don't add just a boiler plate project, atleast make a decent roject before creating a PR as well as follow the CONTRIBUTING.md guidelines to contribute to the repo._

**Comment by Saurabhchaudhary9799** [comment]
hey @047pegasus  , i want to contribute on this  issue , please assign to me

**Comment by 047pegasus** [comment]
Ok sure assigned it you @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
thanks for assigning this issue to me

**Comment by 047pegasus** [comment]
Issue finished!! Well done @Saurabhchaudhary9799 ✅
