### ISSUE TITLE
Enhancement : Improve README.md for Better User Understanding

### ISSUE THREAD

**Issue by Vibgitcode27** [047pegasus/devism#33]
## Description:
The current README.md lacks specific details and might be confusing for new users or contributors. Improving its structure and content will benefit the project by ensuring clarity and making it more accessible.

## 📌 Request for Assignment:
I'd like to work on this issue. Please assign it to me. Please add hacktober fest label for me. Thanks

**Comment by 047pegasus** [comment]
Sure Vibhor Create a good readme for the projecft !! ✅

**Comment by 047pegasus** [comment]
Done Merged ⚡🚀✅
