### ISSUE TITLE
Create a basic CRUD API in Node.js

### ISSUE THREAD

**Issue by 047pegasus** [047pegasus/devism#4]
**Add a self developed baisc CRUP operations supporrted API endpoint project to the repo by learning from a tutorial available online.**

Create a folder with the project name and add all files for project in that folder. Add name of the contributor in the contributor.txt of the project submitted folder.

**Sample Folder Structure:**

<contributor_name>
--- <main_app_folder> (add app files in this sub folder)
--- Contributor.txt (contains name of the contributor)

_Don't add just a boiler plate project, atleast make a decent roject before creating a PR as well as follow the CONTRIBUTING.md guidelines to contribute to the repo._

**Comment by ShashwatPS** [comment]
Can you assign me this issue ? Also one more thing do i have to work on a new branch after forking ?

**Comment by 047pegasus** [comment]
Ok sure. Assigned it you, you can start working now.

**Comment by Sachan-aditya** [comment]
Can you assign me this issue ? Also one more thing do i have to work on a new branch after forking ?

**Comment by 047pegasus** [comment]
Issue closed. Work done ✅
