### ISSUE TITLE
Flutter App Issue

### ISSUE THREAD

**Issue by 047pegasus** [047pegasus/devism#6]
**Add a self developed Flutter App project to the repo by learning from a tutorial available online.**

Create a folder with the project name and add all files for project in that folder. Add name of the contributor in the contributor.txt of the project submitted folder.

**Sample Folder Structure:**

<contributor_name>
--- <main_app_folder> (add app files in this sub folder)
--- Contributor.txt (contains name of the contributor)

_Don't add just a boiler plate project, atleast make a decent roject before creating a PR as well as follow the CONTRIBUTING.md guidelines to contribute to the repo._

**Comment by Sachan-aditya** [comment]
Hello !

I'm excited about contributing to the project, and I'd like to take on the challenge of creating the Flutter app and its documentation. I have experience with Flutter and have successfully developed similar applications in the past.

My Skills:
- Flutter development
- UI/UX design
- Documentation writing

I'm confident that I can deliver a high-quality product within the specified deadline. Please consider assigning me this issue, and I'm ready to dive in and get started!

Looking forward to contributing to the success of our project.

Best,
ADITYA SACHAN

**Comment by 047pegasus** [comment]
Alright assigned issue to you!! 🚀👨‍💻

**Comment by 047pegasus** [comment]
Issue successfully accomplished!! Well done @Sachan-aditya 🚀✅
