### ISSUE TITLE
Typographical Error in the CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by snehalsaurabh** [047pegasus/devism#9]
As the title suggests, there is a small typographical error in the CONTRIBUTING.md file.

**Contributor.txt Details to be entered:**
```
Actual Name:
Username:
Issue ID:
Chnages Summary (in one sentence):
```

As you can observe, there is a small typographical in the above section.

**Comment by snehalsaurabh** [comment]
Kindly assign this to me so I can fix it.

**Comment by 047pegasus** [comment]
Sure assigned it you but it wont be counted as a hacktoberfest compliant contribution as it is a simple task and not an issue that gets resolved with this merge.

**Comment by snehalsaurabh** [comment]
No worries. Thank you for assigning me this task.
